# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-14 00:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0005_auto_20180113_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='city',
            field=models.CharField(default=django.utils.timezone.now, max_length=240),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=960),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slot',
            name='address',
            field=models.CharField(default=django.utils.timezone.now, max_length=240),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slot',
            name='city',
            field=models.CharField(default=django.utils.timezone.now, max_length=240),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slot',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=960),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slot',
            name='location',
            field=models.CharField(default=django.utils.timezone.now, max_length=240),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slot',
            name='state',
            field=models.CharField(default=django.utils.timezone.now, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slot',
            name='zip_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.CharField(max_length=240),
        ),
    ]
