# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-24 12:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_auto_20180124_0740'),
        ('utility', '0013_auto_20180121_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='parentGroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.Group'),
        ),
    ]
