# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-14 01:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0023_user_slot_difference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='parentGroup',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='groups.Group'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_slot',
            name='parentSlot',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='utility.Slot'),
            preserve_default=False,
        ),
    ]
