# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-24 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0030_auto_20180323_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='address',
            field=models.CharField(blank=True, default='hi', max_length=240),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='slot',
            name='city',
            field=models.CharField(blank=True, default='hi', max_length=240),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='slot',
            name='description',
            field=models.CharField(blank=True, default='hi', max_length=960),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='slot',
            name='location',
            field=models.CharField(blank=True, default='hi', max_length=240),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='slot',
            name='paymentPerHour',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='slot',
            name='state',
            field=models.CharField(blank=True, default='hi', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='slot',
            name='zip_code',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
