# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-17 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed', models.CharField(max_length=80)),
                ('color', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=80)),
                ('legs', models.IntegerField(null=True)),
                ('is_dog', models.NullBooleanField()),
            ],
        ),
    ]
