# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-17 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_auto_20180216_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='user',
            field=models.GenericIPAddressField(default='141.134.6.14'),
            preserve_default=False,
        ),
    ]
