# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-17 16:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_auto_20180217_1032'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='alert',
        #     name='ip',
        #     field=models.GenericIPAddressField(default='127.0.0.1'),
        #     preserve_default=False,
        # ),
        # migrations.AlterField(
        #     model_name='alert',
        #     name='user',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        # ),
    ]
