# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-24 12:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0014_event_parentgroup'),
        ('groups', '0004_auto_20180124_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='events',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_event_set', to='utility.Event'),
        ),
        migrations.AddField(
            model_name='group',
            name='slots',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_slot_set', to='utility.Slot'),
        ),
    ]
