# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-19 02:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0009_auto_20180213_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='approvalNeeded',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='pendingUsers',
            field=models.ManyToManyField(related_name='group_pending_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
