# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-09 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='eventName',
            field=models.CharField(blank=True, default='Event', max_length=128),
        ),
        migrations.AddField(
            model_name='profile',
            name='slotName',
            field=models.CharField(blank=True, default='Slot', max_length=128),
        ),
    ]
