# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-14 22:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0002_auto_20180113_1906'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SingleSlot',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='event',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Slot',
        ),
    ]
