# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-11 00:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed_entry',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
