# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-20 16:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed_entry',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 20, 16, 51, 7, 224791, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
