# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-05 19:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_auto_20180630_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed_entry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifs', to=settings.AUTH_USER_MODEL),
        ),
    ]
