# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-10 01:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_feed_entry_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed_entry',
            name='group',
        ),
    ]
