# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-10 01:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_auto_20180203_2224'),
        ('feed', '0005_remove_feed_entry_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed_entry',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.Group'),
            preserve_default=False,
        ),
    ]
