# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-17 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_feed_entry_group'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='feed_entry',
        #     name='user',
        #     field=models.GenericIPAddressField(),
        # ),
    ]
