# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-17 15:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0007_auto_20180217_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed_entry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
