# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-20 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='extraFields',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user_slot',
            name='extraFields',
            field=models.CharField(max_length=240, null=True),
        ),
    ]
