# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 00:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20171202_0547'),
        ('utility', '0002_auto_20171202_0547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singleslot',
            name='organizer',
        ),
        migrations.RemoveField(
            model_name='singleslot',
            name='volunteers',
        ),
        migrations.RemoveField(
            model_name='event',
            name='slots',
        ),
        migrations.AddField(
            model_name='event',
            name='end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='in_person',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='event',
            name='maxVolunteers',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='minVolunteers',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='start',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='volunteers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile'),
        ),
        migrations.DeleteModel(
            name='SingleSlot',
        ),
    ]
