# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-25 18:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0002_auto_20180519_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='parentEvent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utility.Event'),
        ),
    ]
