# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 00:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0003_auto_20171206_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_single',
            field=models.BooleanField(default=False),
        ),
    ]
