# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-25 18:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('utility', '0003_auto_20180525_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='parentGroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.Group'),
        ),
    ]
