# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-03 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0004_slot_parentgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='minVolunteers',
            field=models.IntegerField(null=True),
        ),
    ]
