# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-05 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0005_auto_20180603_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_slot',
            name='accepted',
            field=models.CharField(default='No', max_length=240),
        ),
    ]
