# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-15 20:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0006_auto_20180113_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='title',
            field=models.CharField(default=datetime.datetime(2018, 1, 15, 20, 6, 33, 213524, tzinfo=utc), max_length=240),
            preserve_default=False,
        ),
    ]
