# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-16 00:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0008_event_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.CharField(default=datetime.datetime(2018, 1, 16, 0, 29, 11, 476540, tzinfo=utc), max_length=80),
            preserve_default=False,
        ),
    ]
