# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-19 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0010_auto_20180118_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='maxVolunteers',
            field=models.IntegerField(null=True),
        ),
    ]
