# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-21 17:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0011_auto_20180119_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='volunteers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
