# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-31 04:26
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('utility', '0014_event_parentgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='signin',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 31, 4, 26, 20, 879695, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slot',
            name='signout',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 31, 4, 26, 35, 347449, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='slot',
            name='volunteers',
        ),
        migrations.AddField(
            model_name='slot',
            name='volunteers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
