# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-01 04:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0018_auto_20180131_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='user_slots',
        ),
        migrations.AddField(
            model_name='user_slot',
            name='parentSlot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utility.Slot'),
        ),
    ]
