# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-13 19:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0019_auto_20180131_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='in_person',
        ),
        migrations.RemoveField(
            model_name='event',
            name='maxVolunteers',
        ),
        migrations.RemoveField(
            model_name='event',
            name='minVolunteers',
        ),
    ]
