# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-13 19:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0020_auto_20180213_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='volunteers',
        ),
    ]
