# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-13 19:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0021_remove_event_volunteers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_single',
        ),
        migrations.RemoveField(
            model_name='event',
            name='type',
        ),
    ]
