# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-14 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0022_auto_20180213_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_slot',
            name='difference',
            field=models.FloatField(null=True),
        ),
    ]
