# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-14 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0025_auto_20180214_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_slot',
            name='difference',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
