# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-21 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0026_auto_20180214_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='paymentPerHour',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
