# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-05 21:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat_Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('description', models.CharField(max_length=960)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('tagline', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=960)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('website', models.URLField(blank=True)),
                ('location', models.CharField(max_length=240)),
                ('address', models.CharField(max_length=240)),
                ('city', models.CharField(max_length=240)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.IntegerField(null=True)),
                ('hours', models.IntegerField(default=0)),
                ('approvalNeeded', models.BooleanField()),
                ('organizers', models.ManyToManyField(related_name='group_organizers', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_owner', to=settings.AUTH_USER_MODEL)),
                ('pendingUsers', models.ManyToManyField(related_name='group_pending_users', to=settings.AUTH_USER_MODEL)),
                ('volunteers', models.ManyToManyField(related_name='group_volunteers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='chat_entry',
            name='parentGroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.Group'),
        ),
        migrations.AddField(
            model_name='chat_entry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
