# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-24 00:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utility', '0013_auto_20180121_2332'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=960)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('website', models.URLField(blank=True)),
                ('location', models.CharField(max_length=240)),
                ('address', models.CharField(max_length=240)),
                ('city', models.CharField(max_length=240)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.IntegerField(null=True)),
                ('hours', models.IntegerField(null=True)),
                ('events', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_event_set', to='utility.Event')),
                ('organizers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_organizers', to=settings.AUTH_USER_MODEL)),
                ('slots', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_slot_set', to='utility.Slot')),
                ('volunteers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_volunteers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
