# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-30 21:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_group_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='address',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AlterField(
            model_name='group',
            name='city',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.CharField(blank=True, max_length=960),
        ),
        migrations.AlterField(
            model_name='group',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='location',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AlterField(
            model_name='group',
            name='organizers',
            field=models.ManyToManyField(blank=True, related_name='group_organizers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='pendingUsers',
            field=models.ManyToManyField(blank=True, related_name='group_pending_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='state',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='group',
            name='tagline',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='group',
            name='volunteers',
            field=models.ManyToManyField(blank=True, related_name='group_volunteers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='zip_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
