# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-24 12:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_group_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='events',
        ),
        migrations.RemoveField(
            model_name='group',
            name='slots',
        ),
    ]
