# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-13 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0008_chat_entry_parentgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='hours',
            field=models.IntegerField(default=0),
        ),
    ]
