# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-25 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0010_auto_20180218_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
        migrations.RemoveField(
            model_name='group',
            name='image',
        ),
    ]
